name: Deploy — STAGING

on:
  push:
    branches:
      - staging

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/adrianpuche-padilla-frontend

jobs:
  deploy-staging:
    runs-on: [self-hosted, padilla-frontend]

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push imagen staging
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VITE_API_URL=http://100.84.196.79:9180
          tags: |
            ${{ env.IMAGE }}:staging
            ${{ env.IMAGE }}:staging-${{ github.sha }}

      - name: Deploy servicio STAGING
        run: |
          docker pull ${{ env.IMAGE }}:staging

          if docker service ls | grep -q padilla-frontend-staging; then
            docker service update \
              --image ${{ env.IMAGE }}:staging \
              --with-registry-auth \
              padilla-frontend-staging
          else
            docker service create \
              --name padilla-frontend-staging \
              --network padilla-network-staging \
              --publish 9182:80 \
              --with-registry-auth \
              ${{ env.IMAGE }}:staging
          fi
