name: Deploy — PRODUCCION

on:
  push:
    branches:
      - main

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/adrianpuche-padilla-frontend

jobs:
  deploy-prod:
    runs-on: [self-hosted, padilla-frontend]
    environment: production

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push imagen prod
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VITE_API_URL=http://100.84.196.79:9080
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy servicio PRODUCCION
        run: |
          docker pull ${{ env.IMAGE }}:latest

          if docker service ls | grep -q padilla-frontend-prod; then
            docker service update \
              --image ${{ env.IMAGE }}:latest \
              --with-registry-auth \
              padilla-frontend-prod
          else
            docker service create \
              --name padilla-frontend-prod \
              --network padilla-network-prod \
              --publish 9082:80 \
              --with-registry-auth \
              ${{ env.IMAGE }}:latest
          fi

          sleep 10
          curl -sf http://localhost:9082 && echo "Deploy PROD exitoso" || exit 1
